#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. /opt/openfoam10/etc/bashrc
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# decompose case again
rm -rf processor*
mv log.decomposePar log.decomposePar1
runApplication decomposePar

# runParallel patchSummary
runParallel potentialFoam
runParallel $(getApplication)

runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
