#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

rm -rf 0

# Source tutorial clean functions
. /opt/openfoam10/etc/bashrc
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove surface and features
rm -f constant/geometry/motorBike.obj.gz

cleanCase
cleanExplicitFeatures

#------------------------------------------------------------------------------
