#!/bin/sh

# -- script to create geometry of the case

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. /opt/openfoam10/etc/bashrc
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0

runApplication blockMesh

paraFoam -touch

runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite

runApplication reconstructParMesh -constant
runApplication checkMesh

#------------------------------------------------------------------------------
