#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. /opt/openfoam10/etc/bashrc
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication setFields

mv log.decomposePar log.decomposePar2
runApplication decomposePar -fields
# run custom solver pollutionFoam
rm -rf log.pollutionFoam
runParallel pollutionFoam

rm -f log.reconstructPar
runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
