#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. /opt/openfoam10/etc/bashrc
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# -- reset case
rm -rf 0
cp -r 0.org 0
rm -rf processor*
mv log.decomposePar log.decomposePar1
runApplication decomposePar

# runParallel patchSummary
runParallel potentialFoam
runParallel $(getApplication)

runApplication reco nstructPar -latestTime

#------------------------------------------------------------------------------
